service: node_task

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  memorySize: 512

functions:
  userFunc:
    handler: index.handler
    events:
      - http:
          path: test
          method: get
      - http:
          path: user
          method: get
      - http:
          path: user/{id}
          method: get
      - http:
          path: user
          method: post
      - http:
          path: user/{id}
          method: post
      - http:
          path: user/{id}
          method: delete

plugins:
  - serverless-offline