service: node_task

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  memorySize: 512

functions:
  userFunc:
    handler: index.handler
    events:
      - http:
          path: api/user
          method: get
      - http:
          path: api/user/{id}
          method: get
      - http:
          path: api/user
          method: post
      - http:
          path: api/user/{id}
          method: post
      - http:
          path: api/user/{id}
          method: delete
  profileFunc:
    handler: index.handler
    events:
      - http:
          path: api/profile/{id}
          method: get
      - http:
          path: api/profile
          method: post


plugins:
  - serverless-offline